### ISSUE TITLE
 GPU memory 

### ISSUE THREAD

**Issue by blank-track** [haibo-qiu/CDFormer#1]
Great research, may I ask how much time is required for training and the usage of GPU memory during training

**Comment by haibo-qiu** [comment]
Hi @blank-track,

I'm very sorry for missing your message. On S3DIS, the model needs to be trained for 48 hours using 4 GPUs, and it is recommended to use 32GB of memory.

**Comment by haibo-qiu** [comment]
Feel free to reopen this issue if you have any further questions.
